/*
 * This source file was generated by the Gradle 'init' task
 */
package observer;

public class App {
    public static void main(String[] args) {
        WeatherData weatherData = new WeatherData();

        CurrentConditionsDisplay currentDisplay = new CurrentConditionsDisplay();
        StatisticsDisplay statisticsDisplay = new StatisticsDisplay();

        weatherData.registerObserver(currentDisplay);
        weatherData.registerObserver(statisticsDisplay);

        // 날씨 데이터 변경 시뮬레이션
        System.out.println("=== 첫 번째 날씨 업데이트 ===");
        weatherData.setMeasurements(25.2f, 65.0f, 1013.1f);
        
        System.out.println("\n=== 두 번째 날씨 업데이트 ===");
        weatherData.setMeasurements(27.5f, 70.0f, 1012.5f);
    }
}