/*
 * This source file was generated by the Gradle 'init' task
 */
package observer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.DisplayName;

@DisplayName("날씨 스테이션 애플리케이션 테스트")
class AppTest {
    @Test
    @DisplayName("애플리케이션이 정상적으로 시작되어야 한다")
    void appHasAGreeting() {
        
    }
}
