spring:
  jpa:
    hibernate:
      # naming:
      #   physical-strategy: com.example.buildservice.config.jpa.CustomPhysicalNamingStrategy
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
